### ISSUE TITLE
Reward Scene

### ISSUE THREAD

**Issue by jimver04** [PanMig/Wind-Energy-Lab#11]
Is there any rewarding in the end after everything is accomplished ?
Perhaps a milestone when some easy molecules are accomplished ? A trophy like the "Golden Microscope", "Silver Pipete" ?

Can you place some shortcut keys for cheating ? I do not want to play the whole game to see the reward scenes.

**Comment by PanMig** [comment]
I think you are talking about the Chemistry lab here, not the wind energy.

Yes if you visit the last demo you will find the reward scene when you will exit via the door in the lab.
Yes I can add some shortcuts but I will have to build again, so for the time being try this version

http://160.40.51.48/games/chemistryTest/
