### ISSUE TITLE
Create a default strategy 

### ISSUE THREAD

**Issue by marcmueller86** [PanMig/Wind-Energy-Lab#15]
The default strategy should always be all three scenarios shown, like without content adaptation. 
Therefore, we have to edit the vanish function, if `strategy == null`, do not execute the hiding of the scenarios.

**Comment by PanMig** [comment]
No reason for this actually, I have just changed the code a bit and if strategy is null, no action will take place meaning both 3 panels we show up

```
if (goedle_sdk.GoedleAnalytics.instance.gio_interface.strategy != null){
            GameManager.instance.hold_landscape = goedle_sdk.GoedleAnalytics.instance.gio_interface.strategy["config"][0]["scenario"].Value;
            if (gameObject.name != GameManager.instance.hold_landscape)
                moveGameObject(true);
            else
                moveGameObject(false);
        }
```

**Comment by marcmueller86** [comment]
Default strategy is now, all three landscapes
